config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,
             controllers: { registrations: 'accounts/registrations' }

  authenticated :account do
    root to: redirect('/index'), as: :authenticated_root
  end

  root to: redirect('/accounts/sign_in')

  # Páginas que precisam de login para serem acessadas
  authenticate :account do
    get 'index', to: 'home#index'
    get 'instrucao', to: 'sobre#instrucao'
    get 'sistema', to: 'sobre#sistema'

    resources :aluno_habilidades, only: [:create, :destroy]
    resources :vaga_habilidades, only: [:create, :destroy]
    resources :aluno_vagas, only: [:index, :create, :update, :destroy]
    resources :habilidades
    resources :vagas do
      patch 'update_validacao', on: :member
    end

    resources :empresas, only: [:index, :show, :update, :edit] do
      patch 'update_validacao', on: :member
    end

    resources :alunos, only: [:index, :show, :update, :edit] do
      patch 'update_validacao', on: :member
    end
  end
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  has_many :aluno_habilidades

  has_one :pessoa, as: :papel
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :update_validacao]
  before_action :proibe_aluno, only: [:index]
  before_action :proibe_empresa, only: [:index, :edit, :update]
  before_action :proibe_coordenador, only: [:edit]

  def index
    @alunos = Aluno.all
  end

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Seu perfil foi atualizado!' }
      else
        format.html { render :edit }
      end
    end
  end

  def update_validacao
    @aluno.update(validado: params[:aluno][:status])
    redirect_to alunos_path
  end

  private

  def set_aluno
    @aluno = Aluno.find(params[:id])
  end

  def aluno_params
    params.require(:aluno).permit(:matricula, :periodo)
  end
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |f| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :matricula %>
    <%= f.text_field :matricula, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :periodo %>
    <%= f.text_field :periodo, class: 'form-control' %>
  </div>

  <%= f.submit 'Salvar', class: 'btn btn-success' %>
<% end %>

app/views/alunos/_habilidades.html.erb
<% if current_account.is_aluno? && current_account.perfil.id == @aluno.pessoa.id %>
  <div class="card p-3 mb-3">
    <h5>Adicionar Habilidades</h5>

    <%= form_for AlunoHabilidade.new do |f| %>
      <%= f.hidden_field :aluno_id, value: @aluno.id %>
      <div class="form-row">
        <div class="form-group col">
          <%= f.label :habilidade_id %>
          <%= f.select :habilidade_id, options_from_collection_for_select(Habilidade.all, :id, :nome), {}, class:"form-control" %>
        </div>

        <div class="form-group col">
          <%= f.label :nivel %>
          <%= f.select :nivel, options_for_select([:basico, :intermediario, :avancado]), {}, class:"form-control" %>
        </div>

        <div class="form-group col">
          <label class="d-block">-</label>
          <%= f.submit '+', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>

  </div>
<% end %>

app/views/alunos/_tabela_habilidades.html.erb
<table class="table">
    <thead>
    <tr class="d-flex">
      <th scope="col" class="col-2">Habilidade</th>
      <th scope="col" class="col-4">Descrição</th>
      <th scope="col" class="col-3">Nível</th>
      <th scope="col" class="col-3">Ações</th>
    </tr>
    </thead>
    <tbody>

    <% @aluno.aluno_habilidades.each do |habilidade| %>
      <tr class="d-flex">
        <td class="col-2"><%= habilidade.nome %></td>
        <td class="col-4"><%= habilidade.descricao %></td>
        <td class="col-3"><%= habilidade.nivel %></td>
        <td class="col-3">
            <%= link_to habilidade, method: :delete, class: "btn btn-sm btn-outline-danger" do %>
            <%= fa_icon('times') %> Deletar
            <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

app/views/alunos/_table_aprovados.html.erb
<% if alunos.blank? %>
  <div class="alert alert-info">
    Não existem alunos aprovados.
  </div>
<% else %>
  <table class="table">
    <thead>
    <tr class="d-flex">
      <th scope="col" class="col-3">Nome</th>
      <th scope="col" class="col-2">CPF</th>
      <th scope="col" class="col-2">Matrícula</th>
      <th scope="col" class="col-5">E-mail</th>
    </tr>
    </thead>
    <tbody>
    <% alunos.each do |aluno| %>
      <tr class="d-flex">
        <td class="col-3">
          <%= link_to aluno_path(aluno.id) do %>
            <%= aluno.pessoa.nome %>
          <% end %>
        </td>
        <td class="col-2"><%= aluno.pessoa.cpf %></td>
        <td class="col-2"><%= aluno.matricula %></td>
        <td class="col-5"><%= aluno.pessoa.account.email %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/alunos/_table_espera.html.erb
<% if alunos.blank? %>
  <div class="alert alert-info">
    Não existem alunos em espera para serem validados.
  </div>
<% else %>
  <table class="table">
    <thead>
    <tr class="d-flex">
      <th scope="col" class="col-3">Nome</th>
      <th scope="col" class="col-2">CPF</th>
      <th scope="col" class="col-2">Matrícula</th>
      <th scope="col" class="col-3">E-mail</th>
      <th scope="col" class="col-2">Ações</th>
    </tr>
    </thead>
    <tbody>
    <% alunos.each do |aluno| %>
      <tr class="d-flex">
        <td class="col-3">
          <%= link_to aluno_path(aluno.id) do %>
            <%= aluno.pessoa.nome %>
          <% end %>
        </td>
        <td class="col-2"><%= aluno.pessoa.cpf %></td>
        <td class="col-2"><%= aluno.matricula %></td>
        <td class="col-3"><%= aluno.pessoa.account.email %></td>
        <td class="col-2">
          <div class="row">
            <%= form_for aluno, url: update_validacao_aluno_path(aluno.id) do |f| %>
              <%= f.hidden_field :status, value: true %>
              <%= f.button :submit, class: 'btn btn-success rounded-0' do %>
                <%= fa_icon 'check' %>
              <% end %>
            <% end %>
            <%= form_for aluno, url: update_validacao_aluno_path(aluno.id) do |f| %>
              <%= f.hidden_field :status, value: false %>
              <%= f.button :submit, class: 'btn btn-danger rounded-0' do %>
                <%= fa_icon 'times' %>
              <% end %>
              </div>
            <% end %>
          </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/alunos/_table_reprovados.html.erb
<% if alunos.blank? %>
  <div class="alert alert-info">
    Não existem alunos reprovados.
  </div>
<% else %>
  <table class="table">
    <thead>
    <tr class="d-flex">
      <th scope="col" class="col-3">Nome</th>
      <th scope="col" class="col-2">CPF</th>
      <th scope="col" class="col-2">Matrícula</th>
      <th scope="col" class="col-5">E-mail</th>
    </tr>
    </thead>
    <tbody>
    <% alunos.each do |aluno| %>
      <tr class="d-flex">
        <td class="col-3">
          <%= link_to aluno_path(aluno.id) do %>
            <%= aluno.pessoa.nome %>
          <% end %>
        </td>
        <td class="col-2"><%= aluno.pessoa.cpf %></td>
        <td class="col-2"><%= aluno.matricula %></td>
        <td class="col-5"><%= aluno.pessoa.account.email %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editar Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', aluno_path %>

app/views/alunos/index.html.erb
<h1 class="text-center">Alunos</h1>
<hr/>
<h2 class="pointer-cursor" id="alunos-espera-title">
  Em Espera <%= fa_icon 'angle-down', id: 'espera-icon' %>
</h2>
<div id="alunos-espera-div" style="display: none">
  <%= render partial: 'alunos/table_espera',
             locals: { alunos: @alunos.select { |aluno| aluno.validado == nil } } %>
</div>
<hr>

<h2 class="pointer-cursor text-success" id="alunos-aprovados-title">
  Aprovados <%= fa_icon 'angle-down', id: 'aprovadas-icon' %>
</h2>
<div id="alunos-aprovados-div" style="display: none">
  <%= render partial: 'alunos/table_aprovados',
             locals: { alunos: @alunos.select { |aluno| aluno.validado == true } } %>
</div>
<hr>

<h2 class="pointer-cursor text-danger" id="alunos-reprovados-title">
  Reprovados  <%= fa_icon 'angle-down', id: 'reprovadas-icon' %>
</h2>
<div id="alunos-reprovados-div" style="display: none">
  <%= render partial: 'alunos/table_reprovados',
             locals: { alunos: @alunos.select { |aluno| aluno.validado == false } } %>
</div>

app/views/alunos/show.html.erb
<div class="card p-3 mb-3">
  <div class="row">
    <div class="col-2">
      <%= image_tag "default-user.jpg", class: 'mr-4 rounded border border-gray imagem-lista-vagas'  %>
    </div>

    <div class="col-10">
      <h1><%= @aluno.pessoa.nome %></h1>
      <div class="row">
        <strong class="col-2">E-mail:</strong>
        <%= @aluno.pessoa.account.email %>
      </div>

      <div class="row">
        <strong class="col-2">CPF:</strong>
        <%= @aluno.pessoa.cpf %>
      </div>

      <div class="row">
        <strong class="col-2">Matrícula:</strong>
        <%= @aluno.matricula %>
      </div>

    </div>

  </div>
  <div class="container mt-5">
    <%= render "tabela_habilidades" %>
  </div>

</div>

  <%= render "alunos/habilidades" %>

  <div class="card p-3 mb-3">
    <div class="row">
      <%= link_to 'Voltar', alunos_path, class: 'btn btn-secondary col-1 ml-3' %>
      <% if current_account.is_aluno? && current_account.perfil.papel.id == @aluno.id %>
        <%= link_to 'Editar', edit_aluno_path, class: 'btn btn-outline-info col-1 ml-3' %>
      <% end %>
    </div>
</div>