config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,
             controllers: { registrations: 'accounts/registrations' }

  authenticated :account do
    root to: redirect('/index'), as: :authenticated_root
  end

  root to: redirect('/accounts/sign_in')

  # Páginas que precisam de login para serem acessadas
  authenticate :account do
    get 'index', to: 'home#index'
    get 'instrucao', to: 'sobre#instrucao'
    get 'sistema', to: 'sobre#sistema'

    resources :aluno_habilidades, only: [:create, :destroy]
    resources :vaga_habilidades, only: [:create, :destroy]
    resources :aluno_vagas, only: [:index, :create, :update, :destroy]
    resources :habilidades
    resources :vagas do
      patch 'update_validacao', on: :member
    end

    resources :empresas, only: [:index, :show, :update, :edit] do
      patch 'update_validacao', on: :member
    end

    resources :alunos, only: [:index, :show, :update, :edit] do
      patch 'update_validacao', on: :member
    end
  end
end

app/models/vaga.rb
class Vaga < ApplicationRecord
  belongs_to :empresa
  has_many :vaga_habilidades, dependent: :destroy
  has_many :aluno_vagas, dependent: :destroy
  has_many :habilidades, through: :vaga_habilidades
  delegate :nome, to: :empresa, prefix: true
  delegate :avatar, to: :empresa, prefix: true

  scope :por_empresa, ->(id) { where(empresa_id: id) }
  scope :match_habilidades, ->(aluno) do
    joins(habilidades: :aluno_habilidades)
      .where(aluno_habilidades: { aluno_id: aluno })
      .distinct
  end

  scope :validadas, -> do
    joins(:empresa).where(validada: true, empresas: { validada: true })
  end

  self.per_page = 3

  def disponivel?
    validada? && data_fim > Date.today
  end
end

app/controllers/vagas_controller.rb
class VagasController < ApplicationController
  before_action :set_vaga, only: [:show, :edit, :update, :destroy,
                                  :update_validacao]
  before_action :proibe_aluno, only: [:edit, :update, :update_validacao]
  before_action :proibe_empresa, only: [:update_validacao]
  before_action :proibe_coordenador, only: [:edit, :update, :destroy]
  
  has_scope :por_empresa
  has_scope :match_habilidades

  def index
    index_as_empresa
    index_as_aluno
    index_as_coordenador
  end

  def show; end

  def new
    @vaga = Vaga.new
  end

  def edit; end

  def create
    @vaga = Vaga.new(vaga_params.merge(empresa_id: current_account.perfil_id))
    if @vaga.save
      flash[:success] = 'Vaga foi criada com sucesso.'
      return redirect_to @vaga
    end
    render :new
  end

  def update
    if @vaga.update(vaga_params)
      flash[:succes] = 'Vaga foi atualizada com sucesso.'
      return redirect_to @vaga
    end
    render :edit
  end

  def update_validacao
    salvou = @vaga.update(vaga_params)
    flash[:success] = 'Vaga atualizada com sucesso' if salvou
    flash[:danger] = 'Ocorreu um erro ao atualizar a vaga' unless salvou
    redirect_to vagas_path
  end

  def destroy
    @vaga.destroy
    flash[:success] = 'Vaga foi excluída com sucesso.'
    redirect_to vagas_url
  end

  private

  def index_as_aluno
    return unless current_account.is_aluno?
    @vagas = apply_scopes(Vaga).validadas.
      paginate(:page => params[:page], :per_page => 3)
  end

  def index_as_empresa
    return unless current_account.is_empresa?
    @vagas = Vaga.por_empresa(current_account.perfil_id)
                 .paginate(:page => params[:page], :per_page => 3)
  end

  def index_as_coordenador
    return unless current_account.is_coordenador?
    @vagas = Vaga.all
  end

  def set_vaga
    @vaga = Vaga.find(params[:id])
  end

  def vaga_params
    params.require(:vaga).permit(:titulo, :validada, :descricao,
                                 :data_fim, :data_resposta)
  end
end

app/helpers/vagas_helper.rb
module VagasHelper
  def texto_situacao_vaga(vaga)
    return 'Pendente' if @vaga.validada.nil?
    return 'Aprovada' if @vaga.validada
    'Rejeitada'
  end
end

app/views/vagas/_btn_inscrever_cancelar.html.erb
<% if current_account.is_aluno? && current_aluno.validado? %>
    <% if vaga.disponivel? %>
        <% if vaga.aluno_vagas.por_aluno(current_aluno).any? %>
            <% if vaga.aluno_vagas.por_aluno(current_aluno).last.finalizado? %>
                <%= active_link_to 'Candidatura já avaliada', aluno_vagas_path, class: 'btn btn-info pull-right' %>
            <% else %>
                <%= link_to 'Cancelar Inscrição', vaga.aluno_vagas.pendentes.por_aluno(current_aluno).last,
                            method: :delete,
                            class: 'btn btn-danger pull-right',
                            data: { confirm: 'Você tem certeza?' } %>
            <% end %>
        <% else %>
            <%= form_for AlunoVaga.new do |f| %>
                <%= f.hidden_field :aluno_id, value: current_aluno.id %>
                <%= f.hidden_field :vaga_id, value: vaga.id %>
                <%= f.submit 'Inscrever-se', class: 'btn btn-primary pull-right'%>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/vagas/_filtros.html.erb
<div class="card p-3 mb-3">
<h4>Filtros</h4>
<%= form_tag vagas_path, method: :get do  %>

      <div class="row">
       <div class="col-1">
          <%= label_tag 'Empresa:' %>
        </div>
        <div class="col-4">
          <div class="form-group">
            <%= select_tag :por_empresa, options_from_collection_for_select(Empresa.all, :id, :nome), include_blank: true,
                       class: 'form-control mr-sm-2 select_curso' %>
          </div>
        </div>
      <div class="col-3">
        <div class="form-group form-check form-check-inline">
          <div class="form-control ">
            <%= check_box_tag :match_habilidades, current_account.perfil.papel.id, false, class: "form-check-input" %>
            <%= label_tag :match_habilidades, "Match Habilidades", class:"form-check-label" %>
          </div>
        </div>
      </div>
        <div class="col-4">
          <div class="form-group">
            <%= submit_tag 'Buscar', class: 'btn btn-outline-primary my-2 my-sm-0 w-100 ls-3'  %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/vagas/_form.html.erb
<%= form_with(model: vaga, local: true) do |f| %>
  <% if vaga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vaga.errors.count, "error") %> prohibited this vaga from being saved:</h2>

      <ul>
      <% vaga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo %>
    <%= f.text_field :titulo, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :descricao %>
    <%= f.text_area :descricao, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="form-group col-6">
      <%= f.label :data_fim %>
      <%= f.text_field :data_fim, class: 'form-control datepicker' %>
    </div>

    <div class="form-group col-6">
      <%= f.label :data_resposta %>
      <%= f.text_field :data_resposta, class: 'form-control datepicker' %>
    </div>
  </div>
<div class="row">
  <div class="col-12">
    <%= f.submit 'Salvar', class: 'btn btn-success pull-right' %>
      <% if vaga.persisted? %>
          <%= active_link_to 'Voltar', vaga, class: 'btn btn-primary' %>
      <% else %>
        <%= active_link_to 'Voltar', vagas_path, class: 'btn btn-primary' %>
      <% end %>
  </div>
</div>
<% end %>

app/views/vagas/_habilidades.html.erb
<% if current_account.is_empresa? && current_account.perfil.id == @vaga.empresa.id %>
  <div class="card p-3 mb-3">
    <h5>Adicionar Habilidades</h5>

    <%= form_for VagaHabilidade.new do |f| %>
      <%= f.hidden_field :vaga_id, value: @vaga.id %>
      <div class="form-row">
        <div class="form-group col">
          <%= f.label :habilidade_id %>
          <%= f.select :habilidade_id, options_from_collection_for_select(Habilidade.all, :id, :nome), {}, class:"form-control" %>
        </div>

        <div class="form-group col">
          <%= f.label :nivel %>
          <%= f.select :nivel, options_for_select([:basico, :intermediario, :avancado]), {}, class:"form-control" %>
        </div>

        <div class="form-group col">
          <label class="d-block">-</label>
          <%= f.submit '+', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>

  </div>
<% end %>

app/views/vagas/_index_as_coordenador.html.erb
<h2 class="pointer-cursor" id="espera-title">
  Em Espera <%= fa_icon 'angle-down', id: 'espera-icon' %>
</h2>
<div id="espera-div" style="display: none">
  <%= render partial: 'vagas/table_avaliacao',
             locals: { vagas: vagas.select { |vaga| vaga.validada.nil? },
                       estado_vaga: nil } %>
</div>
<hr>

<h2 class="pointer-cursor text-success" id="aprovadas-title">
  Aprovadas <%= fa_icon 'angle-down', id: 'aprovadas-icon' %>
</h2>
<div id="aprovadas-div" style="display: none">
  <%= render partial: 'vagas/table_avaliacao',
             locals: { vagas: vagas.select { |vaga| vaga.validada == true },
                       estado_vaga: :aprovada } %>
</div>
<hr>

<h2 class="pointer-cursor text-danger" id="reprovadas-title">
  Reprovadas  <%= fa_icon 'angle-down', id: 'reprovadas-icon' %>
</h2>
<div id="reprovadas-div" style="display: none">
  <%= render partial: 'vagas/table_avaliacao',
             locals: { vagas: vagas.select { |vaga| vaga.validada == false },
                       estado_vaga: :reprovada } %>
</div>

app/views/vagas/_tabela_habilidades.html.erb
<% if current_account.is_aluno? || current_account.is_coordenador? %>
<hr>
<h6>Habilidades Desejadas:</h6>
  <% @vaga.vaga_habilidades.each do |habilidade| %>
    <span class="badge badge-pill badge-primary mr-1"><%= habilidade.nome %> : <%= habilidade.nivel %> </span>
  <% end %>
<% end %>


<% if current_account.is_empresa? %>
<table class="table">
    <thead>
    <tr class="d-flex">
      <th scope="col" class="col-2">Habilidade</th>
      <th scope="col" class="col-4">Descrição</th>
      <th scope="col" class="col-3">Nível</th>
      <th scope="col" class="col-3">Ações</th>
    </tr>
    </thead>
    <tbody>

    <% @vaga.vaga_habilidades.each do |habilidade| %>
      <tr class="d-flex">
        <td class="col-2"><%= habilidade.nome %></td>
        <td class="col-4"><%= habilidade.descricao %></td>
        <td class="col-3"><%= habilidade.nivel %></td>
        <td class="col-3">
            <%= link_to habilidade, method: :delete, class: "btn btn-sm btn-outline-danger" do %>
            <%= fa_icon('times') %> Deletar
            <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
    <% end %>

app/views/vagas/_table_avaliacao.html.erb
<% if vagas.blank? %>
    <div class="alert alert-info">
      Não existem vagas <%= estado_vaga.to_s.pluralize %>
    </div>
<% else %>
    <table class="table">
      <thead>
      <tr class="d-flex">
        <th scope="col" class="col-2">Empresa</th>
        <th scope="col" class="col-4">Título</th>
        <th scope="col" class="col-2">Prazo Candidatura</th>
        <th scope="col" class="col-2">Data Resposta</th>
        <th scope="col" class="col-2">Ações</th>
      </tr>
      </thead>
      <tbody>
      <% vagas.each do |vaga| %>
          <tr class="d-flex">
            <td class="col-2">
              <%= link_to empresa_path(vaga.empresa.id) do %>
                  <%= vaga.empresa.nome %>
              <% end %>
            </td>
            <td class="col-4">
              <%= link_to vaga_path(vaga.id) do %>
                <%= vaga.titulo %>
            <% end %>
            </td>
            <td class="col-2"><%= vaga.data_fim.strftime("%d/%m/%Y") %></td>
            <td class="col-2"><%= vaga.data_resposta.strftime("%d/%m/%Y") %></td>
            <td class="col-2">
              <div class="row">
                <% if estado_vaga == :reprovada || estado_vaga.nil? %>
                    <%= form_for vaga, url: update_validacao_vaga_path(vaga.id) do |f| %>
                        <%= f.hidden_field :validada, value: true %>
                        <%= f.button :submit, class: 'btn btn-success rounded-0' do %>
                            <%= fa_icon 'check' %>
                        <% end %>
                    <% end %>
                <% end %>

                <% if estado_vaga == :aprovada || estado_vaga.nil? %>
                    <%= form_for vaga, url: update_validacao_vaga_path(vaga.id) do |f| %>
                        <%= f.hidden_field :validada, value: false %>
                        <%= f.button :submit, class: 'btn btn-danger rounded-0' do %>
                            <%= fa_icon 'times' %>
                        <% end %>
                        </div>
                    <% end %>
                <% end %>
                </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/vagas/edit.html.erb
<h1>Editing Vaga</h1>

<%= render 'form', vaga: @vaga %>

app/views/vagas/index.html.erb
<h1 class="text-center" id="vagasIndex">Vagas</h1>
<% if current_account.is_aluno? %>
    <%= render "vagas/filtros" %>
<% end %>
<% if !current_account.is_coordenador? %>
    <% @vagas.each do |vaga| %>
        <div class="card p-3 mb-3">
          <div class="row">
            <div class="col-md-6">
              <div class="media align-items-center text-muted py-3 px-3">
                <% if vaga.empresa_avatar.present? %>
                    <%= image_tag vaga.empresa_avatar.medium.url, class: 'mr-4 rounded border border-gray imagem-lista-vagas'  %>
                <% else %>
                    <%= image_tag "default_company.png", class: 'mr-4 rounded border border-gray imagem-lista-vagas' %>
                <% end %>
                <p class="media-body pb-3 mb-0 lh-125 pr-5">
                  <strong class="d-block text-gray-dark"><%= vaga.titulo %></strong>
                  <span class="d-block pb-2 small"><%= vaga.empresa_nome %></span>
                  <% vaga.vaga_habilidades.each do |habilidade| %>
                      <span class="badge badge-pill badge-primary mr-1"><%= habilidade.nome %></span>
                  <% end %>
                </p>
              </div>
            </div>
            <div class="col-md-6 d-flex align-self-center align-items-end">
              <%= link_to 'Ver mais detalhes', vaga, class: 'btn btn-outline-primary mx-2 ml-auto' %>

              <%= render partial: 'vagas/btn_inscrever_cancelar', locals: { vaga: vaga } %>
            </div>
          </div>
        </div>
    <% end %>
    <br>
    <% if current_account.is_empresa? %>
        <%= link_to 'Adicionar Vaga', new_vaga_path, class: 'btn btn-primary' %>
    <% end %>
<% else %>
    <%= render partial: 'index_as_coordenador', locals: { vagas: @vagas } %>
<% end %>

<% unless current_account.is_coordenador? %>
  <div class="digg_pagination d-flex justify-content-end">
    <%= will_paginate @vagas, :previous_label => '<', :next_label => '>' %>
  </div>
<% end %>

app/views/vagas/new.html.erb
<h1>Criar Vaga</h1>

<%= render 'form', vaga: @vaga %>

app/views/vagas/show.html.erb
<div class="card p-3 mb-3">
  <div class="row">
    <div class="col-2">
      <% if @vaga.empresa_avatar.present? %>
        <%= image_tag @vaga.empresa_avatar.medium.url %>
      <% else %>
        <%= image_tag "default_company.png" %>
      <% end %>
    </div>

    <div class="col-10">
      <h1>
        <%= @vaga.titulo %>
        <% if current_account.is_empresa? && @vaga.empresa == current_account.perfil %>
            <%= link_to '✖', @vaga, method: :delete, class: 'btn btn-danger pull-right',
                        data: { confirm: 'Você tem certeza que deseja remover esta vaga?' } %>
        <% end %>
      </h1>
      <div class="row">
        <strong class="col-3">Empresa:</strong>
        <%= link_to empresa_path(@vaga.empresa.id) do %>
          <%= @vaga.empresa.nome %>
        <% end %>
      </div>

      <div class="row">
        <strong class="col-3">Descricao:</strong>
        <%= simple_format(@vaga.descricao, {}, wrapper_tag: "span") %>
      </div>

      <div class="row mt-3">
        <strong class="col-3">Prazo Candidatura:</strong>
        <%= @vaga.data_fim.strftime("%d/%m/%Y") %>
      </div>

      <div class="row">
        <strong class="col-3">Data resposta:</strong>
        <%= @vaga.data_resposta.strftime("%d/%m/%Y") %>
      </div>

      <% if current_account.is_empresa? && current_account.perfil.id == @vaga.empresa.id %>
        <div class="row">
          <strong class="col-3">Situação:</strong>
          <%= texto_situacao_vaga @vaga %>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="container mt-5">
   <%= render "tabela_habilidades" %>
  </div>
</div>

<%= render 'vagas/habilidades' %>

<div class="card p-3 mb-3">
    <div class="row">
      <div class="col-12">
      <%= link_to 'Voltar', vagas_path, class: 'btn btn-secondary col-1 pull-left' %>

  <% if current_account.is_empresa? %>
      <%= link_to 'Editar', edit_vaga_path(@vaga), class: 'btn btn-primary col-1 ml-3 pull-right' %>
  <% end %>

      <%= render partial: 'vagas/btn_inscrever_cancelar', locals: { vaga: @vaga } %>
      </div>
    </div>
</div>