config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,
             controllers: { registrations: 'accounts/registrations' }

  authenticated :account do
    root to: redirect('/index'), as: :authenticated_root
  end

  root to: redirect('/accounts/sign_in')

  # Páginas que precisam de login para serem acessadas
  authenticate :account do
    get 'index', to: 'home#index'
    get 'instrucao', to: 'sobre#instrucao'
    get 'sistema', to: 'sobre#sistema'

    resources :aluno_habilidades, only: [:create, :destroy]
    resources :vaga_habilidades, only: [:create, :destroy]
    resources :aluno_vagas, only: [:index, :create, :update, :destroy]
    resources :habilidades
    resources :vagas do
      patch 'update_validacao', on: :member
    end

    resources :empresas, only: [:index, :show, :update, :edit] do
      patch 'update_validacao', on: :member
    end

    resources :alunos, only: [:index, :show, :update, :edit] do
      patch 'update_validacao', on: :member
    end
  end
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  has_many :vagas
  has_one :account, as: :perfil, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  validates :nome, :cnpj, :endereco, presence: true
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :update_validacao]
  before_action :proibe_aluno, only: [:index, :edit, :update, :update_validacao]
  before_action :proibe_empresa, only: [:index, :update_validacao]
  before_action :proibe_coordenador, only: [:edit, :update]

  def index
    @empresas = Empresa.all
  end

  def show; end

  def edit; end

  def update
    if @empresa.update(empresa_params)
      flash[:success] = 'Seu perfil foi atualizado!'
      return redirect_to @empresa
    end
    render :edit
  end

  def update_validacao
    @empresa.update(validada: params[:empresa][:status])
    redirect_to empresas_path
  end

  private

  def set_empresa
    @empresa = Empresa.find(params[:id])
  end

  def empresa_params
    params.require(:empresa).permit(:avatar, :nome, :endereco)
  end
end

app/views/empresas/_form.html.erb
<%= form_with(model: empresa, local: true) do |f| %>
    <% if empresa.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

          <ul>
            <% empresa.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :nome %>
      <%= f.text_field :nome, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :endereco %>
      <%= f.text_field :endereco, class: 'form-control' %>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :avatar %> <br/>
        <%= f.file_field :avatar %>
      </div>
    </div>

    <div class="row">
      <div class="col-12">

        <% if empresa %>
            <%= active_link_to 'Voltar', empresa, class: 'btn btn-primary' %>
        <% else %>
            <%= active_link_to 'Voltar', empresas_path, class: 'btn btn-primary' %>
        <% end %>

        <%= f.submit 'Salvar', class: 'btn btn-success pull-right' %>
      </div>
    </div>
<% end %>

app/views/empresas/_table_avaliacao.html.erb
<% if empresas.blank? %>
    <div class="alert alert-info">
      Não existem empresas <%= estado_empresa.to_s.pluralize %>
    </div>
<% else %>
    <table class="table">
      <thead>
      <tr class="d-flex">
        <th scope="col" class="col-3">Nome</th>
        <th scope="col" class="col-1">CNPJ</th>
        <th scope="col" class="col-3">Endereço</th>

        <% if current_account.is_coordenador? %>
          <th scope="col" class="col-3">E-mail</th>
          <th scope="col" class="col-2">Ações</th>
        <% else %>
          <th scope="col" class="col-5">E-mail</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% empresas.each do |empresa| %>
          <tr class="d-flex">
            <td class="col-3">
              <%= link_to empresa_path(empresa.id) do %>
                  <%= empresa.nome %>
              <% end %>
            </td>
            <td class="col-1"><%= empresa.cnpj %></td>
            <td class="col-3"><%= empresa.endereco %></td>
            <% if current_account.is_coordenador? %>
              <td class="col-3"><%= empresa.account.email %></td>
              <td class="col-2">
                <div class="row">
                  <% if estado_empresa == :reprovada || estado_empresa.nil? %>
                      <%= form_for empresa, url: update_validacao_empresa_path(empresa.id) do |f| %>
                          <%= f.hidden_field :status, value: true %>
                          <%= f.button :submit, class: 'btn btn-success rounded-0' do %>
                              <%= fa_icon 'check' %>
                          <% end %>
                      <% end %>
                  <% end %>

                  <% if estado_empresa == :aprovada || estado_empresa.nil? %>
                      <%= form_for empresa, url: update_validacao_empresa_path(empresa.id) do |f| %>
                          <%= f.hidden_field :status, value: false %>
                          <%= f.button :submit, class: 'btn btn-danger rounded-0' do %>
                              <%= fa_icon 'times' %>
                          <% end %>
                          </div>
                      <% end %>
                  <% end %>
                </td>
            <% else %>
              <td class="col-5"><%= empresa.account.email %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editar Empresa</h1>

<%= render 'form', empresa: @empresa %>

app/views/empresas/index.html.erb
<h1 class="text-center">Empresas</h1>
<hr/>

<% if current_account.is_coordenador? %>
  <h2 class="pointer-cursor" id="empresas-espera-title">
    Em Espera <%= fa_icon 'angle-down', id: 'espera-icon' %>
  </h2>

  <div id="empresas-espera-div" style="display: none">
    <%= render partial: 'empresas/table_avaliacao',
               locals: { empresas: @empresas.select { |empresa| empresa.validada.nil? },
                         estado_empresa: nil } %>
  </div>
  <hr>

  <h2 class="pointer-cursor text-success" id="empresas-aprovadas-title">
    Aprovadas <%= fa_icon 'angle-down', id: 'aprovadas-icon' %>
  </h2>

  <div id="empresas-aprovadas-div" style="display: none">
    <%= render partial: 'empresas/table_avaliacao',
               locals: { empresas: @empresas.select { |empresa| empresa.validada == true },
                         estado_empresa: :aprovada } %>
  </div>
  <hr>

  <h2 class="pointer-cursor text-danger" id="empresas-reprovadas-title">
    Reprovadas  <%= fa_icon 'angle-down', id: 'reprovadas-icon' %>
  </h2>

  <div id="empresas-reprovadas-div" style="display: none">
    <%= render partial: 'empresas/table_avaliacao',
               locals: { empresas: @empresas.select { |empresa| empresa.validada == false },
                         estado_empresa: :reprovada } %>
  </div>
<% end %>

<% if current_account.is_aluno? %>
  <div id="empresas-aprovadas-div">
    <%= render partial: 'empresas/table_avaliacao',
               locals: { empresas: @empresas.select { |empresa| empresa.validada == true },
                         estado_empresa: :aprovada } %>
  </div>
<% end %>

app/views/empresas/show.html.erb
<div class="card p-3 mb-3">
  <div class="row">
    <div class="col-2">
      <% if @empresa.avatar.present? %>
        <%= image_tag @empresa.avatar.medium.url, class: 'mr-4 rounded border border-gray imagem-lista-vagas' %>
      <% else %>
        <%= image_tag "default_company.png", class: 'mr-4 rounded border border-gray imagem-lista-vagas' %>
      <% end %>
    </div>

    <div class="col-10">
      <h1><%= @empresa.nome %></h1>
      <div class="row">
        <strong class="col-2">E-mail:</strong>
        <%= @empresa.account.email %>
      </div>

      <div class="row">
        <strong class="col-2">CNPJ:</strong>
        <%= @empresa.cnpj %>
      </div>

      <div class="row">
        <strong class="col-2">Endereço:</strong>
        <%= @empresa.endereco %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Voltar', url_for(:back), class: 'btn btn-secondary' %>
<% if current_account.is_empresa? && current_account.perfil.id == @empresa.id %>
  <%= link_to 'Editar', edit_empresa_path, class: 'btn btn-outline-info' %>
<% end %>