config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,
             controllers: { registrations: 'accounts/registrations' }

  authenticated :account do
    root to: redirect('/index'), as: :authenticated_root
  end

  root to: redirect('/accounts/sign_in')

  # Páginas que precisam de login para serem acessadas
  authenticate :account do
    get 'index', to: 'home#index'
    get 'instrucao', to: 'sobre#instrucao'
    get 'sistema', to: 'sobre#sistema'

    resources :aluno_habilidades, only: [:create, :destroy]
    resources :vaga_habilidades, only: [:create, :destroy]
    resources :aluno_vagas, only: [:index, :create, :update, :destroy]
    resources :habilidades
    resources :vagas do
      patch 'update_validacao', on: :member
    end

    resources :empresas, only: [:index, :show, :update, :edit] do
      patch 'update_validacao', on: :member
    end

    resources :alunos, only: [:index, :show, :update, :edit] do
      patch 'update_validacao', on: :member
    end
  end
end

app/views/layouts/_devise_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul class="mb-0">
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
          <div class="col-12 text-center">
            Breno Nogueira | Gabriel Rodríguez | Romulo Mourão
          </div>      
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <br/>
        EzEstágio: <%= VERSAO %> <br/>
        Modificado em: <%= File.mtime(Rails.root.join('config', 'initializers', 'version.rb'))
            .in_time_zone('Brasilia').strftime('%d/%m/%Y - %H:%M ') %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_links_aluno.html.erb
<li class="nav-item">
  <%= active_link_to vagas_path, class: 'nav-link' do %>
      <%= fa_icon('briefcase') %> Vagas
  <% end %>
</li>
<li class="nav-item">
  <%= active_link_to aluno_vagas_path, class: 'nav-link' do %>
      <%= fa_icon('list') %> Candidaturas
  <% end %>
</li>

app/views/layouts/_links_coordenador.html.erb
<li class="nav-item">
  <%= active_link_to empresas_path, class: 'nav-link' do %>
    <%= fa_icon('building') %> Empresas
  <% end %>
</li>
<li class="nav-item">
  <%= active_link_to alunos_path, class: 'nav-link' do %>
    <%= fa_icon('users') %> Alunos
  <% end %>
</li>
<li class="nav-item">
  <%= active_link_to vagas_path, class: 'nav-link' do %>
    <%= fa_icon('briefcase') %> Vagas
  <% end %>
</li>
<li class="nav-item">
  <%= active_link_to aluno_vagas_path, class: 'nav-link' do %>
      <%= fa_icon('list') %> Candidaturas
  <% end %>
</li>

app/views/layouts/_links_empresa.html.erb
<li class="nav-item">
  <% if current_account.perfil.validada %>
    <%= active_link_to vagas_path, class: 'nav-link' do %>
      <%= fa_icon('briefcase') %> Vagas
    <% end %>
  <% end %>
</li>
<li class="nav-item">
  <%= active_link_to aluno_vagas_path, class: 'nav-link' do %>
      <%= fa_icon('list') %> Candidaturas
  <% end %>
</li>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">
    <%= image_tag "logo.svg" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if account_signed_in? %>
        <li class="nav-item">
          <%= active_link_to index_path, active: :exact, class: 'nav-link' do %>
            <%= fa_icon('home') %> Home
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon('info') %> Sobre
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= active_link_to 'Instruções', instrucao_path, class: 'dropdown-item' %>
            <%= active_link_to 'Sistema', sistema_path, class: 'dropdown-item' %>
          </div>
        </li>
        <% if current_account.is_empresa? %>
          <%= render 'layouts/links_empresa' %>
        <% end %>
        <% if current_account.is_coordenador? %>
          <%= render 'layouts/links_coordenador' %>
        <% end %>
          <% if current_account.is_aluno? %>
          <%= render 'layouts/links_aluno' %>
          <% end %>
      <% end %>
    </ul>
    <% if account_signed_in? %>
      <span class="navbar-text text-white mr-3">
        Olá,
        <% if current_account.is_empresa? %>
          <%= link_to empresa_path(current_account.perfil.id) do %>
            <b><%= current_account.perfil.nome %></b>!
          <% end %>
        <% elsif current_account.is_aluno? %>
          <%= link_to aluno_path(current_account.perfil.papel.id) do %>
            <b><%= current_account.perfil.nome %></b>!
          <% end %>
        <% else %>
            <b><%= current_account.perfil.nome %></b>!
        <% end %>
      </span>


      <%= link_to 'Sair', destroy_account_session_path, method: :delete, class: 'btn btn-outline-light my-2 my-sm-0' %>
    <% else %>
      <%= active_link_to 'Entrar', new_account_session_path, class: 'btn btn-outline-light my-2 my-sm-0 mr-3' %>
      <%= active_link_to 'Cadastrar', new_account_registration_path, class: 'btn btn-outline-light my-2 my-sm-0' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EzEstagio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="content">
      <div class="container py-5 mt-5 px-5 rounded bg-light text-secondary">
        <%= render 'layouts/devise_alerts' %>

        <% if account_signed_in? && current_account.is_empresa? &&
              !current_account.perfil.validada %>
          <div class="alert alert-warning">
            <span>
              Empresa não validada!</br>
              Por isso não é possível gerenciar vagas.
            </span>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>

      <%= render 'layouts/footer' %>
  </body>
</html>